### ISSUE TITLE
Action Icon not persisting

### ISSUE THREAD

**Issue by tuggernuts** [marekrozmus/react-swipeable-list#14]
Hi, I have your component installed and mostly working. Thank you for making available.

Something I can't figure out: How do you make the action content persist on the screen? I can swipe, and see the action content come into view, but it does not stay in view like in samples. It just slides back out of view when released. 

What am I doing wrong? My code is very similar to your usage example in the Readme. Very simple, just text.

Thanks..

**Comment by marekrozmus** [comment]
Hi :)

Did you set up list type to `IOS` like here:
https://github.com/marekrozmus/react-swipeable-list/blob/cae18105059baee8e9038889d8a3e48703294767/examples/src/ios/WithOneAction.js#L95

If that does not work send me a link to your repository I'll check :)

**Comment by tuggernuts** [comment]
Yes, I did have that enum set.

Here is a really simple example that closely mimics your usage guide: [https://github.com/tuggernuts/react-swipe](url). I just set up this repo with pertinent files.

I'm guessing there is something required that I'm not doing. Thanks!

**Comment by marekrozmus** [comment]
you've got:
`<SwipeableList fullSwipe={false}  ListType={ListType.IOS}>`

and it should be:

`<SwipeableList fullSwipe={false}  type={ListType.IOS}>`

**Comment by tuggernuts** [comment]
Ugh, I knew it was something simple. Thanks.

**Comment by marekrozmus** [comment]
You're welcome. Hope you will build something awesome with this list :)
