### ISSUE TITLE
Is it possible to track the swipe direction?

### ISSUE THREAD

**Issue by v-zdorovcev** [marekrozmus/react-swipeable-list#24]
Is it possible to implement it?
This would look good in `onSwiperProgress`

Eg:
`(progress: number, direction: string) => void`

**Comment by marcussousax** [comment]
Hi, I've found this package today and I'm still testing things, reading issues etc... 
It doesn't seem the best idea, but taking a look at the DOM, maybe you can observe the translate property (inline style). I didn't look the Forks yet, maybe someone have implemented your sugestion..

**Comment by marekrozmus** [comment]
Hi guys :) I will release new version today or at latest tomorrow with that functionality implemented :) @v-zdorovcev - thanks for the proposal.

**Comment by marekrozmus** [comment]
@v-zdorovcev New version 1.6.0 published - please check changes here: https://github.com/marekrozmus/react-swipeable-list/pull/25
Let me know if this is OK :)
