### ISSUE TITLE
Does not work with react-awesome-dnd

### ISSUE THREAD

**Issue by fddayan** [marekrozmus/react-swipeable-list#29]
**Describe the bug**
I'm trying to create a lit with `react-swipeable-list` and `react-awesome-dnd` I'm under the impression both should play nice together, but when I swipe to see the action, the action do not remain, the actions colpast again. If I remove `react-awesome-dnd` it works.

```
 <DragDropContext onDragEnd={onDragEnd(items, uid)}>
      <Droppable droppableId="droppable">
        {(provided1, snapshot) => (
          <div ref={provided1.innerRef} {...provided1.droppableProps} style={getListStyle(snapshot.isDraggingOver)}>
            <SwipeableList
              fullSwipe={false} type={Type.IOS}
            >
              {items.map((timer, index) => (
                <Draggable key={timer.id} draggableId={timer.id} index={index}>
                  {(provided2, snapshot) => (
                    <div
                      ref={provided2.innerRef}
                      {...provided2.draggableProps}
                      style={getItemStyle(snapshot.isDragging, provided2.draggableProps.style)}
                    >
                      <SwipeableListItem trailingActions={trailingActions(theme, timer, handleEditItem)}>
                        <Stack direction='row'>
                          <div {...provided2.dragHandleProps} style={{ alignSelf: 'center' }}>
                            <DragIndicatorIcon sx={{ mr: 1 }} htmlColor='gray' />
                          </div>
                          <Box sx={{ mt: 1, ml: 0, mr: 0 }}>
                            <Typography
                              variant='subtitle1'
                              fontWeight='bold'
                              alignSelf='start'
                              textTransform='capitalize'
                              textAlign='left'
                            >
                              {timer.title}
                            </Typography>
                            <TimerItemContent timer={timer} />
                          </Box>
                        </Stack>
                      </SwipeableListItem>
                    </div>
                  )}
                </Draggable>
              ))}
            </SwipeableList>
          </div>
        )}
      </Droppable>
    </DragDropContext>
```

**Expected behavior**
When I swipe I would expect the actions to remain so I can touch any of them

**Desktop (please complete the following information):**
 - chrome

**Comment by marekrozmus** [comment]
@fddayan Could you please add some GIF or animation what you actually want to achieve?

**Comment by IamAhsanMani** [comment]
@marekrozmus this the behaviour i am facing too.

See below attached gif where i cannot see two action buttons.  When I swipe to see the action, the action do not remain, the actions colpast again.
![issue video](https://user-images.githubusercontent.com/39671392/221109157-4095a74b-9edd-4e51-8dc0-0661875dfd94.gif)

But strange the same code work fine in codesandbox [https://codesandbox.io/s/keen-voice-rohu02](url)
![codesandbox](https://user-images.githubusercontent.com/39671392/221109426-4dfd5b16-b139-4464-9af0-f6aa608cf55d.gif)

**Comment by marekrozmus** [comment]
I am not sure what do you want to achieve with placing `Draggable` as the child of the `SwipeableList`.
The `SwipeableList` expects to have `SwipeableListItem` as a child. It won't work if it will be something else.
So the question is why having `Draggable` as a parent for `SwipeableListItem`?

**Comment by IamAhsanMani** [comment]
@marekrozmus in this comment https://github.com/marekrozmus/react-swipeable-list/issues/29#issuecomment-1442872427 you can see the code sandbox where i provided `SwipeableListItem` as child to `SwipeableList`. But it still didn’t work.

you can see attached gif in above comment.

**Comment by marekrozmus** [comment]
@IamAhsanMani I saw that :) but just wondering what is the reason for using the `Draggable` inside the list?

**Comment by IamAhsanMani** [comment]
@marekrozmus don’t what could be the reason of using `Draggable` inside the list. But in my case it is not work as i didn’t use anything else except `SwipeableListItem`. could you help me to finger out what is the issue with code

**Comment by marekrozmus** [comment]
Closing as the usage is incorrect - it should be:
```
<SwipeableList>
  <SwipeableListItem>
    Item content
  </SwipeableListItem>
</SwipeableList>;
```

and not:
```
<SwipeableList>
  <Draggable>
     <div>
        <SwipeableListItem 
```

please check the readme file.
