### ISSUE TITLE
React does not recognize the x...

### ISSUE THREAD

**Issue by OzoBro** [marekrozmus/react-swipeable-list#32]
Hello, great lib!
I'm getting this warning:
"Warning: React does not recognize the `X` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `actiondelay` instead. If you accidentally passed it from a parent component, remove it from the DOM element."

for:
`actionDelay`, `destructiveCallbackDelay`, `fullSwipe`, `listType`, `scrollStartThreshold` and `swipeStartThreshold`

Using React 18.2.0
I did not get these when using React 17.

Thanks in advance and keep up the good work!

**Comment by gabrielvieiraes** [comment]
@OzoBro How did you resolve this?
