### ISSUE TITLE
Provide a way to click / touch an opened item, toggle all other items to close, including itself

### ISSUE THREAD

**Issue by edwardfxiao** [marekrozmus/react-swipeable-list#37]
Hi there,

1, In many cases, users are only allowed to select actions for a single item at a time. This prevents multiple items from showing actions simultaneously. (Should be closed automatically first one if user tries to open another one)

2, Asking the user to swipe to close an action can be a poor user experience. (Also allowing close by clicking)

Is there any way to improve these?

**Comment by marekrozmus** [comment]
Hi,

Please describe it in more detail - do you mean that if user will open list item and then tries to open another one then the first one should be closed automatically?

**Comment by edwardfxiao** [comment]
https://user-images.githubusercontent.com/11728228/233829277-d7099126-1f0e-4e52-9f1c-1d507feb7753.mov

Like this, always open one at a time

**Comment by edwardfxiao** [comment]
Hi @marekrozmus,
I've revised my comment, and now it should make more sense to understand.

**Comment by marekrozmus** [comment]
@edwardfxiao let me know if the fix is OK for you. Just released 1.8.0 :)

**Comment by edwardfxiao** [comment]
@marekrozmus 
Yes it worked. However, one thing that can still be improved is the ability to close the current item by clicking on it.

On `1.8.0`, Currently, if I open an item and click on it again, it does not close. Instead, it only closes when I click on a different item (which is good). Is there a way to allow the user to close an item by clicking on it again?

**Comment by edwardfxiao** [comment]
Oh, maybe It's because I have multiple `SwipeableList` on the page

```js
{R.filter(i => R.prop('pinned')(i) === true)(conversations).map((item, key)=>{
return <SwipeableListItem key={key}>{item.name}</SwipeableListItem>
})}
{R.filter(i => R.prop('pinned')(i) === false)(conversations).map((item, key)=>{
return <SwipeableListItem key={key}>{item.name}</SwipeableListItem>
})}
```

**Comment by edwardfxiao** [comment]
Okay, I think there are two things that need to be improved:

1, When there is only one `<SwipeableListItem>` on the page, I am unable to close it by clicking on it again.
2, When there are multiple `<SwipeableList>` on the page, it doesn't work at all.

The second issue may be outside your scope, though.

**Comment by edwardfxiao** [comment]
Alternatively, would it be possible for you to provide a reset API that would allow us to manually close the `<SwipeableListItem>` components? 

This could be very useful for users who want to leave multiple items open at once, or for those who prefer to have only one item open at a time.
