### ISSUE TITLE
Max percentage swipable

### ISSUE THREAD

**Issue by lucaskab** [marekrozmus/react-swipeable-list#43]
**Is your feature request related to a problem? Please describe.**
I really like the library but I'm missing the functionality to be able to set a max percentage that the list item can be swipable

**Describe the solution you'd like**
Set a prop to the item for example 50% and then the item will be swipable only for 50% of it's width, and not the 100%

**Describe alternatives you've considered**

**Additional context**

**Comment by marekrozmus** [comment]
Adds @lucaskab as a contributor for ideas.

**Comment by marekrozmus** [comment]
@all-contributors please add @lucaskab for ideas

**Comment by marekrozmus** [comment]
@lucaskab the prop is added in version 1.9.0. Please check :) Enjoy!

**Comment by lucaskab** [comment]
@marekrozmus It's perfect!! Thank you very much, your library is amazing!!
