### ISSUE TITLE
maxSwipe is not optional

### ISSUE THREAD

**Issue by RaulEscobarRivas** [marekrozmus/react-swipeable-list#50]
**Describe the bug**
maxSwipe prop is not optional

https://github.com/marekrozmus/react-swipeable-list/blob/main/src/module.d.ts#L180

**To Reproduce**
1. install latest
2. try to use the `SwipeableListItem` component without passing `maxSwipe` prop

**Expected behavior**
Prop should be optional as per the docs

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 12.3

**Comment by marekrozmus** [comment]
@all-contributors please add @RaulEscobarRivas for bug

**Comment by marekrozmus** [comment]
@RaulEscobarRivas Fixed in 1.9.2

**Comment by RaulEscobarRivas** [comment]
thank you @marekrozmus !
