### ISSUE TITLE
Several actions open if opened after deletion

### ISSUE THREAD

**Issue by Starly26** [marekrozmus/react-swipeable-list#53]
If I open a swipe after deleting a swipeItem using a destructive callback, then when I open the swipe next to it, several actions open, see video.
I think the problem is in https://github.com/marekrozmus/react-swipeable-list/pull/38 since the ID is tied to the index

https://github.com/marekrozmus/react-swipeable-list/assets/86514705/5ede14e0-2d7d-424a-9380-958412b8d8c2

**Comment by marekrozmus** [comment]
@all-contributors please add @Starly26 for bug

**Comment by marekrozmus** [comment]
@Starly26 Fixed in 1.9.3
