### ISSUE TITLE
Why are you tracking mousedown?

### ISSUE THREAD

**Issue by isaachinman** [marekrozmus/react-swipeable-list#64]
Hey there. I've been on the hunt for a package like this, and in general think the behaviour you have achieved is fantastic.

However, I was surprised and disappointed to find that the swipe behaviour still activates on desktop/non touch devices. This is totally unexpected – normally this kind of swipe interaction only applies to mobile/touch devices, and should not even be listening for `mousedown` events.

I'm sure you had a good reason for doing so, but was also surprised to see that this behaviour is not configurable.

Is there any way to prevent the swipe handlers from listening on desktop/non-touch? Are you aware of any other alternative packages?

Thanks 🙏

**Comment by isaachinman** [comment]
That would be fantastic – I was about to fork and start digging myself.

In general I think it would be most useful if this kind of package was a "hooks-only" kind of thing, where the user was responsible for constructing the UI completely on their own.

Besides that, at least having the ability to omit desktop environments would make it usable.

**Comment by marekrozmus** [comment]
This is pretty old package which I update sometimes with some small fixes. You can check the code that there is old stuff like `componentDidMount` ;) The first version was created like 5 years ago here: https://github.com/sandstreamdev/react-swipeable-list
Maybe some day I will do something about but actually there is not so many users that complain about it ;)

**Comment by marekrozmus** [comment]
@isaachinman Please check if this is what you need :) https://github.com/marekrozmus/react-swipeable-list/pull/65

**Comment by isaachinman** [comment]
Yes, I have indeed already had an in-depth look at the source code, and am pondering rewriting it as hooks-only with `react-swipeable` as a sole dependency. If I do that I will let you know!

The PR looks fantastic, thanks for such a rapid fix 👌
